#!/usr/bin/env python3
"""Generate the DSL assets from the live declared option schemas.

Writes two files from ``attachments.dsl_schema()``:

- ``spec/dsl-schema.json`` — the machine-readable schema export consumed
  by editor tooling (deterministic: sorted keys, trailing newline).
- ``docs/dsl-options.md`` — a human-readable cheatsheet with one table per
  group of extensions that share a schema (e.g. all image extensions).

Run from the repo root::

    uv run python scripts/gen_dsl_assets.py

The sync tests in ``tests/test_generated_assets.py`` fail when either file
on disk drifts from the live schema, so regenerate after changing any
processor or source option declarations.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from attachments import dsl_schema

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "spec" / "dsl-schema.json"
DOCS_PATH = REPO_ROOT / "docs" / "dsl-options.md"

GENERATED_WARNING = "GENERATED by scripts/gen_dsl_assets.py — do not edit"

_TABLE_HEADER = (
    "| Option | Type | Aliases | Default | Example | Description |\n"
    "| --- | --- | --- | --- | --- | --- |"
)


def render_schema_json(schema: dict[str, Any]) -> str:
    """Serialize *schema* deterministically (sorted keys, trailing newline)."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _group_keys_by_schema(
    entries: dict[str, list[dict[str, Any]]],
) -> list[tuple[list[str], list[dict[str, Any]]]]:
    """Group keys whose option schemas are identical.

    Returns ``(keys, options)`` pairs with keys sorted inside each group
    and groups ordered by their first key, so output is deterministic.
    """
    keys_by_fingerprint: dict[str, list[str]] = {}
    options_by_fingerprint: dict[str, list[dict[str, Any]]] = {}
    for key in sorted(entries):
        fingerprint = json.dumps(entries[key], sort_keys=True)
        keys_by_fingerprint.setdefault(fingerprint, []).append(key)
        options_by_fingerprint[fingerprint] = entries[key]
    groups = [
        (keys, options_by_fingerprint[fingerprint])
        for fingerprint, keys in keys_by_fingerprint.items()
    ]
    groups.sort(key=lambda group: group[0][0])
    return groups


def _cell(text: str) -> str:
    """Escape a string for use inside a one-line markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


def _option_row(option: dict[str, Any]) -> str:
    """Render one declared option as a markdown table row."""
    aliases = ", ".join(f"`{alias}`" for alias in option["aliases"]) or "—"
    default = "—" if option["default"] is None else f"`{json.dumps(option['default'])}`"
    example = f"`{option['example']}`" if option["example"] else "—"
    return (
        f"| `{option['name']}` | `{option['type']}` | {aliases} "
        f"| {default} | {example} | {_cell(option['help'])} |"
    )


def _render_group(keys: list[str], options: list[dict[str, Any]]) -> str:
    """Render one schema group: a heading plus a table (or a no-options note)."""
    heading = "### " + ", ".join(f"`{key}`" for key in keys)
    if not options:
        return f"{heading}\n\nNo options declared.\n"
    rows = "\n".join(_option_row(option) for option in options)
    return f"{heading}\n\n{_TABLE_HEADER}\n{rows}\n"


def render_options_markdown(schema: dict[str, Any]) -> str:
    """Render the full ``docs/dsl-options.md`` cheatsheet from *schema*."""
    parts = [
        f"<!-- {GENERATED_WARNING} -->",
        "",
        "# DSL options",
        "",
        f"Generated from `attachments.dsl_schema()` (version {schema['version']}).",
        "Regenerate with `uv run python scripts/gen_dsl_assets.py`.",
        "",
        "## Processors",
        "",
    ]
    for keys, options in _group_keys_by_schema(schema["processors"]):
        parts.append(_render_group(keys, options))
    parts.append("## Sources")
    parts.append("")
    for keys, options in _group_keys_by_schema(schema["sources"]):
        parts.append(_render_group(keys, options))
    return "\n".join(parts).rstrip("\n") + "\n"


def main() -> None:
    """Regenerate both assets from the live schema."""
    schema = dsl_schema()
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(render_schema_json(schema), encoding="utf-8")
    DOCS_PATH.write_text(render_options_markdown(schema), encoding="utf-8")
    print(f"wrote {SCHEMA_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {DOCS_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
