#!/usr/bin/env python3
"""Generate the DSL assets from the live declared option schemas.

Writes three files from ``attachments.dsl_schema()``:

- ``spec/dsl-schema.json`` — the machine-readable schema export consumed
  by editor tooling (deterministic: sorted keys, trailing newline).
- ``docs/dsl-options.md`` — a human-readable cheatsheet with one table per
  group of extensions that share a schema (e.g. all image extensions).
- ``src/attachments/__init__.pyi`` — the typing stub that gives editors
  kwargs autocomplete on ``att()``: one named parameter per declared
  option AND alias across all schemas, plus typed ``att.options`` /
  ``att.help``. Re-exports are derived from the real ``__init__.py``.

Run from the repo root::

    uv run python scripts/gen_dsl_assets.py

The sync tests in ``tests/test_generated_assets.py`` fail when any file
on disk drifts from the live schema, so regenerate after changing any
processor or source option declarations (or the public exports).
"""

from __future__ import annotations

import ast
import json
from pathlib import Path
from typing import Any

from attachments import dsl_schema

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "spec" / "dsl-schema.json"
DOCS_PATH = REPO_ROOT / "docs" / "dsl-options.md"
INIT_PATH = REPO_ROOT / "src" / "attachments" / "__init__.py"
STUB_PATH = REPO_ROOT / "src" / "attachments" / "__init__.pyi"

GENERATED_WARNING = "GENERATED by scripts/gen_dsl_assets.py — do not edit"

_TABLE_HEADER = (
    "| Option | Type | Aliases | Default | Example | Description |\n"
    "| --- | --- | --- | --- | --- | --- |"
)


def render_schema_json(schema: dict[str, Any]) -> str:
    """Serialize *schema* deterministically (sorted keys, trailing newline)."""
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _group_keys_by_schema(
    entries: dict[str, list[dict[str, Any]]],
) -> list[tuple[list[str], list[dict[str, Any]]]]:
    """Group keys whose option schemas are identical.

    Returns ``(keys, options)`` pairs with keys sorted inside each group
    and groups ordered by their first key, so output is deterministic.
    """
    keys_by_fingerprint: dict[str, list[str]] = {}
    options_by_fingerprint: dict[str, list[dict[str, Any]]] = {}
    for key in sorted(entries):
        fingerprint = json.dumps(entries[key], sort_keys=True)
        keys_by_fingerprint.setdefault(fingerprint, []).append(key)
        options_by_fingerprint[fingerprint] = entries[key]
    groups = [
        (keys, options_by_fingerprint[fingerprint])
        for fingerprint, keys in keys_by_fingerprint.items()
    ]
    groups.sort(key=lambda group: group[0][0])
    return groups


def _cell(text: str) -> str:
    """Escape a string for use inside a one-line markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip() or "—"


def _option_row(option: dict[str, Any]) -> str:
    """Render one declared option as a markdown table row."""
    aliases = ", ".join(f"`{alias}`" for alias in option["aliases"]) or "—"
    default = "—" if option["default"] is None else f"`{json.dumps(option['default'])}`"
    example = f"`{option['example']}`" if option["example"] else "—"
    return (
        f"| `{option['name']}` | `{option['type']}` | {aliases} "
        f"| {default} | {example} | {_cell(option['help'])} |"
    )


def _render_group(keys: list[str], options: list[dict[str, Any]]) -> str:
    """Render one schema group: a heading plus a table (or a no-options note)."""
    heading = "### " + ", ".join(f"`{key}`" for key in keys)
    if not options:
        return f"{heading}\n\nNo options declared.\n"
    rows = "\n".join(_option_row(option) for option in options)
    return f"{heading}\n\n{_TABLE_HEADER}\n{rows}\n"


def render_options_markdown(schema: dict[str, Any]) -> str:
    """Render the full ``docs/dsl-options.md`` cheatsheet from *schema*."""
    parts = [
        f"<!-- {GENERATED_WARNING} -->",
        "",
        "# DSL options",
        "",
        f"Generated from `attachments.dsl_schema()` (version {schema['version']}).",
        "Regenerate with `uv run python scripts/gen_dsl_assets.py`.",
        "",
        "## Processors",
        "",
    ]
    for keys, options in _group_keys_by_schema(schema["processors"]):
        parts.append(_render_group(keys, options))
    parts.append("## Sources")
    parts.append("")
    for keys, options in _group_keys_by_schema(schema["sources"]):
        parts.append(_render_group(keys, options))
    return "\n".join(parts).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Typing stub (src/attachments/__init__.pyi) — kwargs autocomplete for att()
# ---------------------------------------------------------------------------

#: Declared option type -> Python type expression in the stub.
STUB_TYPE_MAP = {
    "pages": "int | str | tuple[int, int]",
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "bool_or_auto": "bool | str",
    "str_or_int": "str | int",
}

#: Deterministic ordering for merged union pieces.
_UNION_PIECE_ORDER = ("bool", "int", "float", "str", "tuple[int, int]")


def _parse_init_exports() -> tuple[list[tuple[str, str]], list[str]]:
    """Parse the real ``__init__.py``: re-export pairs and ``__all__``.

    Returns ``(reexports, all_names)`` where *reexports* is the list of
    ``(module, name)`` pairs from relative imports, in source order, and
    *all_names* is the declared ``__all__``. Raises if the two drift
    (every public name except ``att`` must come from a relative import;
    ``att`` is declared in the stub via the ``_Att`` class).
    """
    tree = ast.parse(INIT_PATH.read_text(encoding="utf-8"))
    reexports: list[tuple[str, str]] = []
    all_names: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level == 1 and node.module:
            reexports.extend((node.module, alias.name) for alias in node.names)
        if isinstance(node, ast.Assign):
            targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
            if targets == ["__all__"]:
                all_names = ast.literal_eval(node.value)
    if not all_names:
        raise RuntimeError(f"could not find __all__ in {INIT_PATH}")
    imported = {name for _, name in reexports}
    missing = set(all_names) - imported - {"att"}
    if missing:
        raise RuntimeError(
            f"__all__ names without a relative import in {INIT_PATH}: {missing}"
        )
    return reexports, all_names


def _merge_types(mapped_types: set[str]) -> str:
    """Merge mapped type expressions for one option name across schemas.

    A single declared type is used verbatim; differing declarations are
    merged into a deterministic union of their pieces.

    Examples (one type vs. ``bool`` + ``bool_or_auto`` collision):
        >>> _merge_types({"str | int"})
        'str | int'
        >>> _merge_types({"bool", "bool | str"})
        'bool | str'
    """
    if len(mapped_types) == 1:
        return next(iter(mapped_types))
    pieces = {piece for t in mapped_types for piece in t.split(" | ")}
    return " | ".join(p for p in _UNION_PIECE_ORDER if p in pieces)


def stub_option_params(schema: dict[str, Any]) -> list[tuple[str, str]]:
    """One ``(param_name, type_expr)`` per declared option AND alias.

    Covers every schema (processors and sources). Aliases get the same
    type as their canonical option. Deterministic order: groups sorted
    alphabetically by canonical name; within a group the canonical name
    first, then its aliases alphabetically. A name colliding with another
    group's canonical (or already emitted) is skipped.
    """
    groups: dict[str, dict[str, set[str]]] = {}
    for section in ("processors", "sources"):
        for option_dicts in schema[section].values():
            for option in option_dicts:
                group = groups.setdefault(
                    option["name"], {"types": set(), "aliases": set()}
                )
                group["types"].add(STUB_TYPE_MAP[option["type"]])
                group["aliases"].update(option["aliases"])
    params: list[tuple[str, str]] = []
    seen: set[str] = set()
    for canonical in sorted(groups):
        type_expr = _merge_types(groups[canonical]["types"])
        if canonical not in seen:
            params.append((canonical, type_expr))
            seen.add(canonical)
        for alias in sorted(groups[canonical]["aliases"]):
            if alias in seen or alias in groups:
                continue
            params.append((alias, type_expr))
            seen.add(alias)
    return params


def render_init_stub(schema: dict[str, Any]) -> str:
    """Render ``src/attachments/__init__.pyi`` from *schema* + ``__init__.py``."""
    reexports, all_names = _parse_init_exports()
    lines = [
        f"# {GENERATED_WARNING}",
        '"""Typed public surface of attachments (kwargs autocomplete for att())."""',
        "",
        "from typing import Any, Literal",
        "",
    ]
    # ``att`` is intentionally NOT re-exported: it is declared below as an
    # ``_Att`` instance so both its call signature and att.options/att.help
    # are typed.
    lines += [
        f"from .{module} import {name} as {name}"
        for module, name in reexports
        if name in all_names and name != "att"
    ]
    lines += ["", "__all__ = ["]
    lines += [f'    "{name}",' for name in all_names]
    lines += [
        "]",
        "",
        "__version__: str",
        "",
        "class _Att:",
        "    def __call__(",
        "        self,",
        "        input: str,",
        "        *,",
        "        api_key: str | None = ...,",
        '        prefer: Literal["local", "service", "local-only", "service-only"]'
        " | None = ...,",
    ]
    lines += [
        f"        {name}: {type_expr} = ...,"
        for name, type_expr in stub_option_params(schema)
    ]
    lines += [
        "        **options: Any,",
        "    ) -> Artifacts: ...",
        "    def options(",
        "        self, key: str | None = None",
        "    ) -> dict[str, Any] | list[dict[str, Any]]: ...",
        "    def help(self) -> None: ...",
        "",
        "att: _Att",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Regenerate all three assets from the live schema."""
    schema = dsl_schema()
    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(render_schema_json(schema), encoding="utf-8")
    DOCS_PATH.write_text(render_options_markdown(schema), encoding="utf-8")
    STUB_PATH.write_text(render_init_stub(schema), encoding="utf-8")
    print(f"wrote {SCHEMA_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {DOCS_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {STUB_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
