# GENERATED by scripts/gen_dsl_assets.py — do not edit
"""Typed public surface of attachments (kwargs autocomplete for att())."""

from typing import Any, Literal

from ._artifacts import Artifacts as Artifacts
from ._options import Option as Option
from ._options import dsl_schema as dsl_schema
from ._options import options as options
from ._options import register_options as register_options
from ._processors import get_processors_copy as get_processors_copy
from ._processors import processor as processor
from ._processors import processors as processors
from ._processors import register_processor as register_processor
from ._processors import reset_processors as reset_processors
from ._sources import extra_unpack_handlers as extra_unpack_handlers
from ._sources import register_unpack_handler as register_unpack_handler
from ._sources import source as source
from ._sources import unpack as unpack
from .config import configure as configure
from .config import get_config as get_config
from .config import reset_config as reset_config
from .deps import check_dep as check_dep
from .deps import check_deps as check_deps
from .deps import has_local as has_local
from .deps import has_service as has_service
from .dsl import format_dsl as format_dsl
from .dsl import parse_dsl as parse_dsl
from .render import chunk as chunk
from .render import render_text as render_text
from .render import to_claude_content as to_claude_content
from .render import to_claude_messages as to_claude_messages
from .render import to_openai_messages as to_openai_messages
from .types import ERROR_INVALID_OPTION as ERROR_INVALID_OPTION
from .types import ERROR_MISSING_DEPENDENCY as ERROR_MISSING_DEPENDENCY
from .types import ERROR_PARSE as ERROR_PARSE
from .types import ERROR_PASSWORD_REQUIRED as ERROR_PASSWORD_REQUIRED
from .types import ERROR_PROCESSING as ERROR_PROCESSING
from .types import ERROR_SERVICE as ERROR_SERVICE
from .types import ERROR_UNPACK as ERROR_UNPACK
from .types import Artifact as Artifact
from .types import ErrorInfo as ErrorInfo
from .types import ImageItem as ImageItem
from .types import Meta as Meta
from .types import Processor as Processor
from .types import Segment as Segment
from .types import error_artifact as error_artifact
from .types import is_missing_dependency as is_missing_dependency
from .types import make_artifact as make_artifact
from .types import missing_dep_artifact as missing_dep_artifact
from .types import normalize_artifact as normalize_artifact

__all__ = [
    "att",
    "Artifacts",
    "Artifact",
    "ImageItem",
    "Meta",
    "Segment",
    "ErrorInfo",
    "Processor",
    "make_artifact",
    "error_artifact",
    "missing_dep_artifact",
    "is_missing_dependency",
    "normalize_artifact",
    "ERROR_MISSING_DEPENDENCY",
    "ERROR_PASSWORD_REQUIRED",
    "ERROR_PARSE",
    "ERROR_UNPACK",
    "ERROR_SERVICE",
    "ERROR_INVALID_OPTION",
    "ERROR_PROCESSING",
    "configure",
    "get_config",
    "reset_config",
    "parse_dsl",
    "format_dsl",
    "Option",
    "options",
    "register_options",
    "dsl_schema",
    "check_deps",
    "check_dep",
    "has_local",
    "has_service",
    "render_text",
    "to_claude_content",
    "to_claude_messages",
    "to_openai_messages",
    "chunk",
    "processors",
    "register_processor",
    "processor",
    "reset_processors",
    "get_processors_copy",
    "unpack",
    "register_unpack_handler",
    "source",
    "extra_unpack_handlers",
]

__version__: str

class _Att:
    def __call__(
        self,
        input: str,
        *,
        api_key: str | None = ...,
        prefer: Literal["local", "service", "local-only", "service-only"] | None = ...,
        delimiter: str = ...,
        sep: str = ...,
        dpi: int = ...,
        images: bool | str = ...,
        render: bool | str = ...,
        max_dim: int = ...,
        max_pages: int = ...,
        pages: int | str | tuple[int, int] = ...,
        page: int | str | tuple[int, int] = ...,
        password: str = ...,
        pw: str = ...,
        ref: str = ...,
        branch: str = ...,
        tag: str = ...,
        rotate: int = ...,
        rows: int = ...,
        limit: int = ...,
        max_rows: int = ...,
        select: str = ...,
        css: str = ...,
        sheet: str | int = ...,
        summary: bool = ...,
        **options: Any,
    ) -> Artifacts: ...
    def options(
        self, key: str | None = None
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    def help(self) -> None: ...

att: _Att
